version: '2'
services:
  wisefarmer-mysql:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Shanghai
    restart: always
    container_name: wisefarmer-mysql
    image: wisefarmer-mysql
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --default-authentication-plugin=caching_sha2_password
    ports:
      - 3306:3306

  wisefarmer-redis:
    image: redis:5.0
    ports:
      - 6379:6379
    restart: always
    hostname: wisefarmer-redis
    container_name: wisefarmer-redis

  wisefarmer-system:
    build:
      context: ./jeecg-module-system/jeecg-system-start
    restart: on-failure
    depends_on:
      - wisefarmer-mysql
      - wisefarmer-redis
    container_name: wisefarmer-system
    image: wisefarmer-system
    hostname: wisefarmer-system
    ports:
      - 8080:8080
