version: '2'
services:
  wisefarmer-nacos:
    restart: always
    build:
      context: ./jeecg-cloud-nacos
    ports:
      - 8848:8848
    container_name: wisefarmer-nacos
    hostname: wisefarmer-nacos

  wisefarmer-system:
    depends_on:
      - wisefarmer-nacos
    build:
      context: ./jeecg-system-cloud-start
    container_name: jeecg-system-start
    hostname: wisefarmer-system
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai

  wisefarmer-demo:
    depends_on:
      - wisefarmer-nacos
    build:
      context: ./jeecg-demo-cloud-start
    container_name: jeecg-demo-start
    hostname: wisefarmer-demo
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai

  wisefarmer-gateway:
    restart: on-failure
    build:
      context: ./jeecg-cloud-gateway
    ports:
      - 9999:9999
    depends_on:
      - wisefarmer-nacos
      - wisefarmer-system
    container_name: wisefarmer-gateway
    hostname: wisefarmer-gateway

#  wisefarmer-sentinel:
#    restart: on-failure
#    build:
#      context: ./jeecg-visual/jeecg-cloud-sentinel
#    ports:
#      - 9000:9000
#    depends_on:
#      - wisefarmer-nacos
#      - wisefarmer-demo
#      - wisefarmer-system
#      - wisefarmer-gateway
#    container_name: wisefarmer-sentinel
#    hostname: wisefarmer-sentinel
#
#  wisefarmer-xxljob:
#    build:
#      context: ./jeecg-visual/jeecg-cloud-xxljob
#    ports:
#      - 9080:9080
#    container_name: wisefarmer-xxljob
#    hostname: wisefarmer-xxljob
